"""agent workspace runs and briefs

Revision ID: 3e8f23eb950f
Revises: ce3fb0608e74
Create Date: 2026-08-19 21:51:24.417101
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e8f23eb950f'
down_revision: str | None = 'ce3fb0608e74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_executions',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('proposal_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_agent_action_executions_actor_user_id'), 'agent_action_executions', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_agent_action_executions_proposal_id'), 'agent_action_executions', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_agent_action_executions_trace_id'), 'agent_action_executions', ['trace_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('organization_workspace_id', sa.String(), nullable=True),
    sa.Column('agent_workspace_id', sa.String(), nullable=True),
    sa.Column('agent_profile', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('requested_scope', sa.String(), nullable=False),
    sa.Column('policy_decision', sa.String(), nullable=False),
    sa.Column('policy_reason', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("policy_decision IN ('ALLOW', 'DENY', 'MASK', 'REQUIRE_APPROVAL')", name='ck_agent_run_policy_decision'),
    sa.CheckConstraint("status IN ('success', 'partial', 'error', 'denied')", name='ck_agent_run_status'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['agent_workspace_id'], ['agent_workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_actor_created', 'agent_runs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_actor_user_id'), 'agent_runs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_trace_id'), 'agent_runs', ['trace_id'], unique=False)
    op.create_table('workspace_briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_workspace_id', sa.String(), nullable=False),
    sa.Column('agent_workspace_id', sa.String(), nullable=False),
    sa.Column('brief_type', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('brief_json', sa.JSON(), nullable=False),
    sa.CheckConstraint("brief_type IN ('delivery', 'quality')", name='ck_workspace_brief_type'),
    sa.ForeignKeyConstraint(['agent_workspace_id'], ['agent_workspaces.id'], ),
    sa.ForeignKeyConstraint(['organization_workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_briefs_agent_workspace_id'), 'workspace_briefs', ['agent_workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_briefs_generated_at'), 'workspace_briefs', ['generated_at'], unique=False)
    op.create_index(op.f('ix_workspace_briefs_organization_workspace_id'), 'workspace_briefs', ['organization_workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_briefs_trace_id'), 'workspace_briefs', ['trace_id'], unique=False)
    op.create_index('ix_workspace_briefs_workspace_type_generated', 'workspace_briefs', ['agent_workspace_id', 'brief_type', 'generated_at'], unique=False)
    op.add_column('tasks', sa.Column('agent_workspace_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('confidence', sa.Float(), nullable=True))
    # server_default is required here (unlike the other new nullable columns above/below): this is
    # a NOT NULL column being added to a table that may already have rows, and Postgres backfills
    # existing rows from the DDL's own default - a Python-side `default=False` on the model has no
    # effect on ALTER TABLE, only on rows the ORM itself inserts afterwards.
    op.add_column(
        'tasks',
        sa.Column('needs_clarification', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('tasks', sa.Column('work_item_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('quality_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_agent_workspace_id'), 'tasks', ['agent_workspace_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'agent_workspaces', ['agent_workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_agent_workspace_id'), table_name='tasks')
    op.drop_column('tasks', 'quality_status')
    op.drop_column('tasks', 'severity')
    op.drop_column('tasks', 'work_item_type')
    op.drop_column('tasks', 'needs_clarification')
    op.drop_column('tasks', 'confidence')
    op.drop_column('tasks', 'agent_workspace_id')
    op.drop_index('ix_workspace_briefs_workspace_type_generated', table_name='workspace_briefs')
    op.drop_index(op.f('ix_workspace_briefs_trace_id'), table_name='workspace_briefs')
    op.drop_index(op.f('ix_workspace_briefs_organization_workspace_id'), table_name='workspace_briefs')
    op.drop_index(op.f('ix_workspace_briefs_generated_at'), table_name='workspace_briefs')
    op.drop_index(op.f('ix_workspace_briefs_agent_workspace_id'), table_name='workspace_briefs')
    op.drop_table('workspace_briefs')
    op.drop_index(op.f('ix_agent_runs_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_actor_user_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_actor_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_action_executions_trace_id'), table_name='agent_action_executions')
    op.drop_index(op.f('ix_agent_action_executions_proposal_id'), table_name='agent_action_executions')
    op.drop_index(op.f('ix_agent_action_executions_actor_user_id'), table_name='agent_action_executions')
    op.drop_table('agent_action_executions')
    # ### end Alembic commands ###
