"""task release target

Revision ID: 5fdc2d9a547c
Revises: 3e8f23eb950f
Create Date: 2026-08-20 17:37:10.596062
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5fdc2d9a547c'
down_revision: str | None = '3e8f23eb950f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('release_target', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_release_target'), 'tasks', ['release_target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_release_target'), table_name='tasks')
    op.drop_column('tasks', 'release_target')
    # ### end Alembic commands ###
