import { useState } from 'react'
import PageHeader from '../components/common/PageHeader'
import SettingsSection from '../components/profile/SettingsSection'

export default function ProfilePage(){const [saved,setSaved]=useState(false);const save=()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)};return <div className="page-container profile-page"><PageHeader eyebrow="Account" title="Profile & settings" description="Manage your personal details and Orbit preferences." action={<button className="btn btn-primary" onClick={save}><i className={`bi ${saved?'bi-check2':'bi-floppy'} me-2`}/>{saved?'Saved':'Save changes'}</button>}/><div className="profile-layout"><aside className="profile-card"><div className="profile-avatar">AR<button><i className="bi bi-camera"/></button></div><h2>Alex Rivera</h2><p>alex.rivera@orbit.co</p><span>Product Designer</span><div className="profile-completion"><div><strong>Profile completion</strong><b>85%</b></div><div className="progress"><div className="progress-bar" style={{width:'85%'}}/></div></div><nav><a href="#basic" className="active"><i className="bi bi-person"/>Basic information</a><a href="#preferences"><i className="bi bi-sliders"/>Preferences</a><a href="#notifications"><i className="bi bi-bell"/>Notifications</a><a href="#ai"><i className="bi bi-stars"/>AI settings</a><a href="#security"><i className="bi bi-shield-lock"/>Security</a></nav></aside><div className="settings-stack">
      <SettingsSection icon="bi-person" title="Basic information" description="Your personal details and contact information."><div className="form-grid"><label><span>Full name</span><input className="form-control" defaultValue="Alex Rivera"/></label><label><span>Email address</span><input className="form-control" defaultValue="alex.rivera@orbit.co"/></label><label><span>Job title</span><input className="form-control" defaultValue="Product Designer"/></label><label><span>Timezone</span><select className="form-select" defaultValue="bangkok"><option value="bangkok">Bangkok (GMT+7)</option><option>London (GMT+0)</option><option>New York (GMT-5)</option></select></label></div></SettingsSection>
      <SettingsSection icon="bi-sliders" title="Preferences" description="Customize how Orbit works for you."><div className="form-grid"><label><span>Preferred language</span><select className="form-select"><option>English</option><option>Thai</option><option>Spanish</option></select></label><label><span>Default reminder time</span><select className="form-select"><option>30 minutes before</option><option>15 minutes before</option><option>1 hour before</option></select></label></div></SettingsSection>
      <SettingsSection icon="bi-bell" title="Notifications" description="Choose where and when you want to be notified."><SettingToggle title="Desktop notifications" detail="Tasks, reminders, and mentions" checked/><SettingToggle title="Email digest" detail="A daily summary delivered at 8:00 AM" checked/><SettingToggle title="AI suggestion alerts" detail="When Orbit finds a new task or event"/></SettingsSection>
      <SettingsSection icon="bi-stars" title="AI settings" description="Control Orbit's access and defaults."><div className="form-grid"><label><span>Default permission scope</span><select className="form-select"><option>20 latest messages</option><option>50 latest messages</option><option>Unread messages</option></select></label><label><span>AI response detail</span><select className="form-select"><option>Concise</option><option>Balanced</option><option>Detailed</option></select></label></div><SettingToggle title="Personalized suggestions" detail="Use memory to make AI results more relevant" checked/></SettingsSection>
      <SettingsSection icon="bi-shield-lock" title="Security" description="Keep your account safe."><div className="security-row"><div><strong>Password</strong><p>Last changed 3 months ago</p></div><button className="btn btn-light">Change password</button></div></SettingsSection>
    </div></div></div>}

function SettingToggle({title,detail,checked=false}){return <div className="setting-toggle"><div><strong>{title}</strong><p>{detail}</p></div><div className="form-check form-switch"><input className="form-check-input" type="checkbox" defaultChecked={checked}/></div></div>}
