import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { AuthShell, GoogleAuthButton } from './LoginPage'
import { useAuth } from '../context/AuthContext'

export default function RegisterPage(){const {register,handleSubmit,watch,formState:{errors}}=useForm();const nav=useNavigate();const {register:signUp}=useAuth();const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false)
  const onSubmit=async({name,email,password})=>{setError('');setSubmitting(true);try{await signUp(email,password,name);nav('/chat')}catch(err){setError(err.detail||'Could not create account')}finally{setSubmitting(false)}}
  return <AuthShell title="Create your account" subtitle="Get started with your intelligent workspace."><form onSubmit={handleSubmit(onSubmit)}>{error&&<div className="auth-error">{error}</div>}<label className="auth-label">Full name</label><div className={`auth-input ${errors.name?'invalid':''}`}><i className="bi bi-person"/><input placeholder="Alex Rivera" {...register('name',{required:true})}/></div><label className="auth-label mt-3">Email address</label><div className={`auth-input ${errors.email?'invalid':''}`}><i className="bi bi-envelope"/><input placeholder="you@company.com" {...register('email',{required:true,pattern:/^\S+@\S+\.\S+$/})}/></div><div className="auth-two"><label><span className="auth-label">Password</span><div className={`auth-input ${errors.password?'invalid':''}`}><i className="bi bi-lock"/><input type="password" placeholder="Min. 6 characters" {...register('password',{required:true,minLength:6})}/></div></label><label><span className="auth-label">Confirm password</span><div className={`auth-input ${errors.confirm?'invalid':''}`}><i className="bi bi-lock"/><input type="password" placeholder="Repeat password" {...register('confirm',{validate:v=>v===watch('password')})}/></div></label></div><label className="remember"><input type="checkbox" {...register('terms',{required:true})}/> I agree to the <a href="#">Terms of Service</a></label>{errors.terms&&<small className="text-danger d-block">Please accept the terms to continue.</small>}<button className="btn btn-primary w-100 auth-submit" disabled={submitting}>{submitting?'Creating account...':'Create account'} <i className="bi bi-arrow-right"/></button><GoogleAuthButton onError={setError}/><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></form></AuthShell>}
