import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { AuthShell, GoogleAuthButton } from './LoginPage'
import { useAuth } from '../context/AuthContext'

export default function RegisterPage(){const {register,handleSubmit,watch,formState:{errors}}=useForm();const nav=useNavigate();const {register:signUp}=useAuth();const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false)
  const onSubmit=async({name,email,password})=>{setError('');setSubmitting(true);try{await signUp(email.trim().toLowerCase(),password,name.trim());nav('/login',{replace:true,state:{registrationSuccess:true,email:email.trim().toLowerCase()}})}catch(err){setError(typeof err.detail==='string'?err.detail:'Could not create account')}finally{setSubmitting(false)}}
  return <AuthShell title="Create your account" subtitle="Get started with your intelligent workspace."><form onSubmit={handleSubmit(onSubmit)} noValidate>{error&&<div className="auth-error">{error}</div>}<label className="auth-label">Full name</label><div className={`auth-input ${errors.name?'invalid':''}`}><i className="bi bi-person"/><input placeholder="Alex Rivera" autoComplete="name" {...register('name',{required:'Full name is required.',validate:value=>value.trim().length>0||'Full name is required.'})}/></div>{errors.name&&<small className="text-danger">{errors.name.message}</small>}<label className="auth-label mt-3">Email address</label><div className={`auth-input ${errors.email?'invalid':''}`}><i className="bi bi-envelope"/><input type="email" placeholder="you@company.com" autoComplete="email" {...register('email',{required:'Email address is required.',pattern:{value:/^\S+@\S+\.\S+$/,message:'Enter a valid email address.'}})}/></div>{errors.email&&<small className="text-danger">{errors.email.message}</small>}<div className="auth-two"><label><span className="auth-label">Password</span><div className={`auth-input ${errors.password?'invalid':''}`}><i className="bi bi-lock"/><input type="password" placeholder="Min. 6 characters" autoComplete="new-password" {...register('password',{required:'Password is required.',minLength:{value:6,message:'Password must be at least 6 characters.'}})}/></div>{errors.password&&<small className="text-danger">{errors.password.message}</small>}</label><label><span className="auth-label">Confirm password</span><div className={`auth-input ${errors.confirm?'invalid':''}`}><i className="bi bi-lock"/><input type="password" placeholder="Repeat password" autoComplete="new-password" {...register('confirm',{required:'Please confirm your password.',validate:value=>value===watch('password')||'Passwords do not match.'})}/></div>{errors.confirm&&<small className="text-danger">{errors.confirm.message}</small>}</label></div><label className="remember"><input type="checkbox" {...register('terms',{required:'Please accept the terms to continue.'})}/> I agree to the Terms of Service</label>{errors.terms&&<small className="text-danger d-block">{errors.terms.message}</small>}<button className="btn btn-primary w-100 auth-submit" disabled={submitting}>{submitting?'Creating account...':'Create account'} <i className="bi bi-arrow-right"/></button><GoogleAuthButton onError={setError}/><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></form></AuthShell>}
